config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  resources :users, controller: "registrations", only: [:new, :create] do
    resources :articles do
      resources :comments
    end
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates_associated :comments

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
end

app/models/concerns/visible.rb
module Visible 
  extend ActiveSupport::Concern

  VALID_STATUES = ["public", "private", "archived"]

  included do
    validates :status, inclusion: { in: VALID_STATUES }
  end

  class_methods do
    def public_count 
      where(status: "public").count
    end
  end

  def archived?
    status == "archived"
  end

end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes

  attribute :user

end

app/models/user.rb
class User < ApplicationRecord
  before_save do
    self.email = "add_your_email@host.com"
  end

  has_many :articles, dependent: :destroy

  has_secure_password

  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticate
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_user_articles

  def index
    @articles = @articles.all
  end

  def show
    @article = @articles.find(params[:id])
  end

  def new
    @article = @articles.new
  end

  def create
    @article = @articles.new(article_params)
    if @article.save
      redirect_to [@user, @article]
    else
      render :new
    end
  end

  def edit
    @article = @articles.find(params[:id])
  end
  
  def update
    @article = @articles.find(params[:id])
      if @article.update(article_params)
        redirect_to [@user, @article]
      else
        render :edit
      end
  end

  def destroy
    @article = @articles.find(params[:id])
    @article.destroy
    redirect_to user_articles_path(@user)
  end

  private

    def article_params 
      params.require(:article).permit(:title, :body, :status)
    end

    def find_user_articles
      @user = Current.user
      @articles = @user.articles
    end
end
 

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_article_comments

  def create
    @comment = @comments.create(comment_params)
    redirect_to user_article_path(Current.user, @article)
  end

  def destroy
    @comments.find_by(id: params[:id]).destroy
    redirect_to user_article_path(Current.user, @article)
  end

  private 
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end

    def find_article_comments 
      @articles = Current.user.articles
      @article = @articles.find_by(id: params[:article_id])
      @comments = @article.comments
    end
end

app/controllers/concerns/authenticate.rb
module Authenticate 
  extend ActiveSupport::Concern

  included do 
    before_action :set_user, :authenticate
  end

  private 
    def authenticate 
      if Current.user.nil?
        redirect_to login_url
      end
    end

    def is_logged_in
      if session[:user_id]
        redirect_to user_articles_path(Current.user)
      end
    end

    def set_user 
      if session[:user_id]
        Current.user = User.find_by(id: session[:user_id])
      else 
        Current.user = nil 
      end
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  skip_before_action :authenticate
  before_action :is_logged_in

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      session[:user_id] = @user.id
      Current.user = @user
      redirect_to user_articles_path(@user)
    else
      render :new
    end
  end

  private
    def user_params 
      params.require(:user).permit(:email, :password)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authenticate
  before_action :is_logged_in

  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user.present? && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      Current.user = @user
      redirect_to user_articles_path(@user)
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: [user, article] do |f| %>
  <ul>
    <% article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <br>
  <div>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </div>
  <br>
  <div>
    <%= f.label :body %> <br>
    <%= f.text_area :body %>
  </div>
  <br>
  <div>
    <%= f.label :status %> <br>
    <%= f.select :status, ["public", "private", "archived"], selected: "public" %>
  </div>
  <br>
  <div>
    <%= f.submit article.persisted? ? "Edit" : "Save" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", user: @user, article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

Our blog has <%= Article.public_count %> articles and counting!

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, [@user, article] %>
    </li>
  <% end %>
</ul>

<%= link_to "Create Article", new_user_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", user: @user, article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>

<p><%= link_to "Edit", [:edit, @user, @article] %></p>
<p><%= link_to "Delete", [@user, @article], method: :delete, data: { confirm: "Are you sure?" } %></p>

<h3>Comments</h3>
<%= render @article.comments %>

<h4>Add a comment:</h4>
<%= render "comments/form" %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment</strong>
  <%= comment.body %>
</p>

<p><%= link_to "delete comment", [comment.article.user, comment.article, comment], method: :delete, data: { confirm: "Are you sure?" } %></p>

app/views/comments/_form.html.erb
<%= form_with model: [ Current.user, @article, @article.comments.build ] do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <div>
    <%= f.label :status %> <br>
    <%= f.select :status, ["public", "private", "archived"], selected: "public" %>
  </div>
  <p>
    <%= f.submit "Add comment" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>